[package]
name    = "rust-demo-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum  = "0.5.6"
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread"] }

[[bin]]
name = "rust-demo-server"
path = "src/main.rs"
