# fly.toml file generated for rust-demo-server on 2022-05-24T17:40:46+07:00

app = "rust-demo-server"

kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[env]

[experimental]
cmd           = "rust-demo-server"
auto_rollback = true

[[services]]
internal_port = 8080
protocol      = "tcp"

[[services.ports]]
handlers = ["http"]
port     = 80

[[services.ports]]
handlers = ["tls", "http"]
port     = 443

[[services.http_checks]]
path            = "/health"
method          = "get"
timeout         = "2000"
interval        = "10000"
protocol        = "http"
grace_period    = "5s"
tls_skip_verify = false
